#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: client_client server_server

client_client: 
	$(MAKE) -C Client all -f Makefile

server_server: 
	$(MAKE) -C Server all -f Makefile

clean: clean_client_client clean_server_server

clean_client_client: 
	$(MAKE) -C Client clean -f Makefile

clean_server_server: 
	$(MAKE) -C Server clean -f Makefile

.PHONY: clean_client_client clean_server_server

